### ISSUE TITLE
How to generate the ground truth model 'model.mat'

### ISSUE THREAD

**Issue by jianchaoci** [zhanhz/pcnbv_pytorch#2]

**Comment by zhanhz** [comment]
Hey, I have

**Comment by zhanhz** [comment]
Hey, I have uploaded [sample_mesh](https://github.com/zhanhz/PC-NBV_pytorch/tree/main/sample_mesh) to help you to solve your problem. You can run [batch_tran.m](https://github.com/zhanhz/PC-NBV_pytorch/blob/main/sample_mesh/batch_tran.m) through matlab to generate the ground truth data. Hope this will help you.

**Comment by jianchaoci** [comment]
> Hey, I have uploaded [sample_mesh](https://github.com/zhanhz/PC-NBV_pytorch/tree/main/sample_mesh) to help you to solve your problem. You can run [batch_tran.m](https://github.com/zhanhz/PC-NBV_pytorch/blob/main/sample_mesh/batch_tran.m) through matlab to generate the ground truth data. Hope this will help you.

Hi, really thanks for your help!!👍
